/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tqbao.studentmanagement.View.StudentManagement;

import com.tqbao.studentmanagement.Controller.CertificateController;
import com.tqbao.studentmanagement.Controller.StudentController;
import com.tqbao.studentmanagement.DAO.ConnectionDB;
import com.tqbao.studentmanagement.Model.Student;
import com.tqbao.studentmanagement.Model.User;
import com.tqbao.studentmanagement.View.AccountManagement.Dashboard;

import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Objects;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static com.tqbao.studentmanagement.DAO.CertificateDAO.GET_ALL_CERTIFICATE;

/**
 *
 * @author tqbao
 */
public class Students extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    public Students() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        updateCertificateCombobox();
        getStudents();

        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnCancel.setEnabled(false);
    }

    public Students(String role) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        if (role.equals("Employee")) {
            crud.setVisible(false);
        }
        updateCertificateCombobox();
        getStudents();

        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnCancel.setEnabled(false);
    }

    DefaultTableModel dtm;
    StudentController studentController = new StudentController();
    CertificateController certificateController = new CertificateController();
    
    private void updateCertificateCombobox() {
        certificateController.getAll(txtCertificate1);
    }

    private void getStudents() {
        studentController.showStudents(listStudent, dtm);
    }

    private java.sql.Date convertToSqlDate(Object obj) {
        if (obj instanceof java.util.Date) {
            return new java.sql.Date(((java.util.Date) obj).getTime());
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listStudent = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        btnSortByCertificate = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        btnSortByName = new javax.swing.JButton();
        jPanel44 = new javax.swing.JPanel();
        btnSortByDate = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        btnSortByGrade = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        searchStudentPhone = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        searchStudentName = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnViewAll = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        crud = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txtCertificate1 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        txtGrade = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel24 = new javax.swing.JPanel();
        txtGender = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        txtPhone = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(940, 544));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Birthday", "Gender", "Phone", "Address", "Grade", "Certificate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listStudent);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 560, 350));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSortByCertificate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSortByCertificate.setText("Sort  By Certificate");
        btnSortByCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByCertificateActionPerformed(evt);
            }
        });
        jPanel39.add(btnSortByCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        jPanel26.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 50));

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, 60));

        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 60));

        jPanel26.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 560, 60));

        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSortByName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSortByName.setText("Sort By Name");
        btnSortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByNameActionPerformed(evt);
            }
        });
        jPanel40.add(btnSortByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel26.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 50));

        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSortByDate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSortByDate.setText("Sort By Date");
        btnSortByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByDateActionPerformed(evt);
            }
        });
        jPanel44.add(btnSortByDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel26.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, 50));

        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSortByGrade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSortByGrade.setText("Sort By Grade");
        btnSortByGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByGradeActionPerformed(evt);
            }
        });
        jPanel45.add(btnSortByGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanel26.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 50));

        jPanel4.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 560, 50));

        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel32.add(searchStudentPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        jPanel13.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 40));

        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel33.add(searchStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        jPanel13.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 40));

        jPanel36.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 80));

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Student Phone");
        jPanel30.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 40));

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Student Name");
        jPanel31.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        jPanel28.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanel36.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 80));

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 80));

        jPanel37.setBackground(new java.awt.Color(204, 255, 255));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel37.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel10.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel37.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel35.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 150, 80));

        jPanel4.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 580, 510));

        crud.setBackground(new java.awt.Color(255, 255, 255));
        crud.setMinimumSize(new java.awt.Dimension(350, 350));
        crud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        crud.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(237, 237, 238));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new java.awt.Color(242, 242, 242));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Student Management");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel20.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Certificate");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 90, 40));

        jPanel9.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Grade");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, 40));

        jPanel11.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jPanel12.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date");
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 40));

        jPanel14.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gender");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, 40));

        jPanel15.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone");
        jPanel15.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 90, 40));

        jPanel16.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Address");
        jPanel16.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 90, 30));

        jPanel5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 290));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCertificate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null" }));
        jPanel17.add(txtCertificate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        jPanel18.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        jPanel18.add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 40));

        jPanel21.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        jPanel22.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        jPanel24.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel24.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        jPanel25.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel25.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        jPanel27.setPreferredSize(new java.awt.Dimension(90, 50));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel27.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel7.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 250, 290));

        jPanel20.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 310));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 430));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel38.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jPanel23.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 50));

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel46.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jPanel23.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 50));

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel47.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 30));

        jPanel23.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 50));

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel48.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 30));

        jPanel23.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 70, 50));

        jPanel19.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 340, 50));

        crud.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 510));

        jPanel1.add(crud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listStudentMouseClicked
        // TODO add your handling code here:
        dtm = (DefaultTableModel) listStudent.getModel();
        int selectIndex = listStudent.getSelectedRow();
//        int id = (int) dtm.getValueAt(selectIndex, 0);
        String name = dtm.getValueAt(selectIndex, 1).toString();
        Date birthday =  convertToSqlDate(dtm.getValueAt(selectIndex,2));

        String gender = (String) dtm.getValueAt(selectIndex, 3);
        String phone = (String) dtm.getValueAt(selectIndex, 4);
        String address = (String) dtm.getValueAt(selectIndex, 5);
        String grade = (String) dtm.getValueAt(selectIndex, 6);
        String certificate = (String) dtm.getValueAt(selectIndex, 7);

        txtName.setText(name);
        txtDate.setDate(convertToSqlDate(birthday));
        txtGender.setSelectedItem(gender);
        txtPhone.setText(phone);
        txtAddress.setText(address);
        txtGrade.setSelectedItem(grade);
        txtCertificate1.setSelectedItem(certificate);


        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_listStudentMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        Date birthday;
        if (txtDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Birthday must not be null");
            return;
        }
        birthday = new java.sql.Date(txtDate.getDate().getTime());

        String gender = (String) txtGender.getSelectedItem();
        String phone = txtPhone.getText();
        String address = txtAddress.getText();
        String grade = (String) txtGrade.getSelectedItem();
        String certificate = (String) txtCertificate1.getSelectedItem();
        System.out.println("C: " + certificate);
        if (!name.equals("")) {
            if (phone.length() < 10) {
                JOptionPane.showMessageDialog(this, "Phone number must be greater than 10 digits");
                txtPhone.requestFocus();
            } else if (!phone.chars().allMatch( Character::isDigit)){
                JOptionPane.showMessageDialog(this, "Phone number must not contain characters");
                txtPhone.requestFocus();
            } else {
                Student student;
                if (certificate.equals("Null")) {
                    student = new Student(name, birthday, gender, phone, address, grade);
                } else {
                    student = new Student(name, birthday, gender, phone, address, grade, certificate);
                }
                studentController.add(student);

                JOptionPane.showMessageDialog(this, "Student has been added");

                txtName.setText("");

                txtGender.setSelectedItem(-1);
                txtPhone.setText("");
                txtAddress.setText("");
                txtGrade.setSelectedIndex(0);
                txtCertificate1.setSelectedIndex(0);
                getStudents();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please provide details");
            txtName.requestFocus();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        dtm = (DefaultTableModel) listStudent.getModel();
        int selectIndex = listStudent.getSelectedRow();

        int id = (int) dtm.getValueAt(selectIndex, 0);
        String name = txtName.getText();
        Date birthday = convertToSqlDate(txtDate.getDate());
        String gender = (String) txtGender.getSelectedItem();
        String phone = txtPhone.getText();
        String address = txtAddress.getText();
        String grade = (String) txtGrade.getSelectedItem();
        String certificate = (String) txtCertificate1.getSelectedItem();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Check again with your information");
            txtName.requestFocus();
        } else if(!phone.chars().allMatch(Character::isDigit) && phone.length() < 10) {
            JOptionPane.showMessageDialog(this, "Check again with your information");
            txtPhone.grabFocus();
        }else {
            Student student;
            if (certificate.equals("Null")) {
                student = new Student(id, name, birthday, gender, phone, address, grade);
            } else {
                student = new Student(id, name, birthday, gender, phone, address, grade, certificate);
            }

            studentController.update(student);

            JOptionPane.showMessageDialog(this,  "Student has been updated");

            btnAdd.setEnabled(true);
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnCancel.setEnabled(false);
            txtName.setText("");
            txtGender.setSelectedItem(-1);
            txtPhone.setText("");
            txtAddress.setText("");
            txtGrade.setSelectedIndex(0);
            txtCertificate1.setSelectedIndex(0);
            getStudents();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        dtm = (DefaultTableModel) listStudent.getModel();
        int selectIndex = listStudent.getSelectedRow();

        int id = (int) dtm.getValueAt(selectIndex, 0);
        int result = JOptionPane.showConfirmDialog(this, "Are you sure to delete student?", "", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            studentController.delete(id);

            JOptionPane.showMessageDialog(this, "Student has been deleted");

            btnAdd.setEnabled(true);
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnCancel.setEnabled(false);
            txtName.setText("");

            txtGender.setSelectedItem(-1);
            txtPhone.setText("");
            txtAddress.setText("");
            txtGrade.setSelectedIndex(0);
            txtCertificate1.setSelectedIndex(0);
            getStudents();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnCancel.setEnabled(false);
        txtName.setText("");

        txtGender.setSelectedItem(-1);
        txtPhone.setText("");
        txtAddress.setText("");
        txtGrade.setSelectedIndex(0);
        txtCertificate1.setSelectedIndex(0);
        getStudents();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String name = searchStudentName.getText();
        String phone = searchStudentPhone.getText();

        if (name.equals("") || phone.equals("")) {
            JOptionPane.showMessageDialog(this, "Please provide information");
            if (name.equals("")) {
                searchStudentName.requestFocus();
            } else {
                searchStudentPhone.requestFocus();
            }
        } else if (!phone.chars().allMatch(Character::isDigit)) {
            JOptionPane.showMessageDialog(this, "Phone must not contain character");
            searchStudentPhone.requestFocus();
        } else {
            Student student = studentController.showExistedStudent(name, phone);

            if (student != null) {
                dtm = (DefaultTableModel) listStudent.getModel();
                dtm.setRowCount(0);

                Vector v = new Vector();
                v.add(student.getId());
                v.add(student.getName());
                v.add(student.getBirthday());
                v.add(student.getPhone());
                v.add(student.getAddress());
                v.add(student.getGrade());
                v.add(student.getCertificate());
                dtm.addRow(v);
            } else {
                dtm = (DefaultTableModel) listStudent.getModel();
                dtm.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Invalid student infomation");
            }
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        getStudents();

    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnSortByGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByGradeActionPerformed
        // TODO add your handling code here:
        studentController.sortByGrade(listStudent, dtm);
    }//GEN-LAST:event_btnSortByGradeActionPerformed

    private void btnSortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByNameActionPerformed
        // TODO add your handling code here:
        studentController.sortByName(listStudent, dtm);
    }//GEN-LAST:event_btnSortByNameActionPerformed

    private void btnSortByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByDateActionPerformed
        // TODO add your handling code here:
        studentController.sortByDate(listStudent, dtm);
    }//GEN-LAST:event_btnSortByDateActionPerformed

    private void btnSortByCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByCertificateActionPerformed
        // TODO add your handling code here:
        studentController.sortByCertificate(listStudent, dtm);
    }//GEN-LAST:event_btnSortByCertificateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSortByCertificate;
    private javax.swing.JButton btnSortByDate;
    private javax.swing.JButton btnSortByGrade;
    private javax.swing.JButton btnSortByName;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JPanel crud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listStudent;
    private javax.swing.JTextField searchStudentName;
    private javax.swing.JTextField searchStudentPhone;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JComboBox<String> txtCertificate1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JComboBox<String> txtGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
